// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/oj.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	JudgeRelay_Connect_FullMethodName = "/oj.JudgeRelay/Connect"
)

// JudgeRelayClient is the client API for JudgeRelay service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// JudgeRelay is the bidi stream between the API server and one judge daemon.
// Daemons connect outwards (no inbound firewall hole on judge machines) and
// the API pushes tasks down the same stream results arrive on.
type JudgeRelayClient interface {
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DaemonMessage, ApiMessage], error)
}

type judgeRelayClient struct {
	cc grpc.ClientConnInterface
}

func NewJudgeRelayClient(cc grpc.ClientConnInterface) JudgeRelayClient {
	return &judgeRelayClient{cc}
}

func (c *judgeRelayClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DaemonMessage, ApiMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &JudgeRelay_ServiceDesc.Streams[0], JudgeRelay_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DaemonMessage, ApiMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type JudgeRelay_ConnectClient = grpc.BidiStreamingClient[DaemonMessage, ApiMessage]

// JudgeRelayServer is the server API for JudgeRelay service.
// All implementations must embed UnimplementedJudgeRelayServer
// for forward compatibility.
//
// JudgeRelay is the bidi stream between the API server and one judge daemon.
// Daemons connect outwards (no inbound firewall hole on judge machines) and
// the API pushes tasks down the same stream results arrive on.
type JudgeRelayServer interface {
	Connect(grpc.BidiStreamingServer[DaemonMessage, ApiMessage]) error
	mustEmbedUnimplementedJudgeRelayServer()
}

// UnimplementedJudgeRelayServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedJudgeRelayServer struct{}

func (UnimplementedJudgeRelayServer) Connect(grpc.BidiStreamingServer[DaemonMessage, ApiMessage]) error {
	return status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedJudgeRelayServer) mustEmbedUnimplementedJudgeRelayServer() {}
func (UnimplementedJudgeRelayServer) testEmbeddedByValue()                    {}

// UnsafeJudgeRelayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JudgeRelayServer will
// result in compilation errors.
type UnsafeJudgeRelayServer interface {
	mustEmbedUnimplementedJudgeRelayServer()
}

func RegisterJudgeRelayServer(s grpc.ServiceRegistrar, srv JudgeRelayServer) {
	// If the following call pancis, it indicates UnimplementedJudgeRelayServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&JudgeRelay_ServiceDesc, srv)
}

func _JudgeRelay_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(JudgeRelayServer).Connect(&grpc.GenericServerStream[DaemonMessage, ApiMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type JudgeRelay_ConnectServer = grpc.BidiStreamingServer[DaemonMessage, ApiMessage]

// JudgeRelay_ServiceDesc is the grpc.ServiceDesc for JudgeRelay service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JudgeRelay_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "oj.JudgeRelay",
	HandlerType: (*JudgeRelayServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _JudgeRelay_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/oj.proto",
}
